### ISSUE TITLE
GitHub personal access token

### ISSUE THREAD

**Issue by integratecology** [ecoisilva/movedesign#1]
I had issues installing the movedeisgn app (Error 403), so here is how I got around that to get it to install correctly:

**Step 1**: Generate a GitHub personal access token by entering 

`usethis::create_github_token()`

in the console. This will take you to GitHub and generate a token. Configure the token (or just scroll down and generate it using the default settings) and copy it to your clipboard.

**Step 2**: Save the personal access token in your R environment. Return to RStudio and enter

`usethis::edit_r_environ()`

in the console. This opens a new window in RStudio. When that window opens, write:

`GITHUB_PAT="GITHUB_PERSONAL_ACCESS_TOKEN"`

where GITHUB_PERSONAL_ACCESS_TOKEN is the token (a string of letters and numbers) you just copied from GitHub.

**Step 3**: Save this file, close it, and restart R. After that, you should be good able to install movedesign.

**Comment by ecoisilva** [comment]
Thank you, I've added this documentation to a vignette on installation issues.
