### ISSUE TITLE
Number of individuals to track

### ISSUE THREAD

**Issue by Lisark45** [ecoisilva/movedesign#4]
Hi there,

I know movedesign can estimate precision for an estimator based on sampling duration and frequency,
but I wonder if you have any advice on the optimal number of individuals to track to estimate home size?

Or would I get the sampling duration that gave me the best precision, (say it was 8 weeks), and say that was equivalent to tracking 1 individual for 8 weeks, or 4 individuals for 2 weeks each?

Thanks

**Comment by ecoisilva** [comment]
I apologize for the delay, I was teaching a workshop. 
The outputted sampling duration for best precision is on an individual basis, so you should ideally track every individual for a minimum of 8 weeks in your example. For the optimal number of individuals to track, if are you interested in getting the mean home range for the sampled population, you can test that in the new development version, albeit with slightly more complexity in interpretation, as biases may arise from both the sampling design and the number of individuals tracked.
When you navigate to the meta-analyses tab, if you see that the majority of individual home ranges are underestimated, my recommendation is to prioritize increasing the sampling duration before considering increasing the number of individuals tracked. If you have more specific questions, let me know.

**Comment by Lisark45** [comment]
Thank you. I'll look forward to when the new development version is released.
